//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbempresainvEntities : DbContext
    {
        public dbempresainvEntities()
            : base("name=dbempresainvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<modulo> modulo { get; set; }
        public virtual DbSet<operacion> operacion { get; set; }
        public virtual DbSet<rol_operacion> rol_operacion { get; set; }
        public virtual DbSet<ustate> ustate { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<categoria_producto> categoria_producto { get; set; }
    
        public virtual ObjectResult<string> sp_buscarProducto(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_buscarProducto", nombreParameter);
        }
    }
}
